//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE2024
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public decimal ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public decimal RoleID { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
